name: 'Publish'
on:
  release:
    types: [published]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Extract version
        id: version
        uses: olegtarasov/get-tag@v2.1
        with:
          tagRegex: 'v(.*)'

      - name: Create NPM config
        run: |
          echo "//registry.npmjs.org/:_authToken="${{secrets.NPM_TOKEN}}"" > ~/.npmrc
        shell: sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Build
        run: npx nx run core:build
      - name: Publish
        run: npx nx run core:publish --args='--ver=$VER'
        env:
          VER: ${{ steps.version.outputs.tag }}
